os:
  - linux
  - osx
language: c++
compiler: clang
sudo: required
before_install:
  - bash .travis.d/install_linux_dependencies.sh
  - bash .travis.d/install_osx_dependencies.sh
script: make && make test
after_success: bash .travis.d/cov.sh

