os:
  - linux
  - osx
addons:
  apt:
    packages:
      - libcppunit-dev
      - libsdl2-dev
before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install cppunit; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install sdl2; fi
language: c++
compiler: clang
script: make && make test

