os:
  - linux
  - osx
before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sh .travis.d/install_linux_dependencies.sh; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then sh .travis.d/install_linux_dependencies.sh; fi
language: c++
compiler: clang
script: make && make test

