os:
  - linux
  - osx
language: c++
compiler: clang
sudo: required
before_install:
  - sh .travis.d/install_linux_dependencies.sh
  - sh .travis.d/install_osx_dependencies.sh
script: make && make test
after_success: sh ./cov.sh

